name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust with wasm target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.87.0
          target: wasm32-unknown-unknown
          override: true

      - name: Build project
        run: cargo build -r --target wasm32-unknown-unknown

      - name: Prepare site
        run: |
          mkdir dist
          cp -r web/* dist/
          cp target/wasm32-unknown-unknown/release/*.wasm dist/

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
